---
# yamllint disable rule:truthy
# yamllint disable rule:line-length
- name: ASA OG Working
  connection: network_cli
  hosts: asa_firewalls
  gather_facts: no
  become: yes
  become_method: enable

  tasks:

    - name: "TASK 1: Set RFC1918 Object Group"
      asa_og:
        name: RFC1918_Networks
        group_type: network-object
        state: present
        description: RFC1918 Local Networks
        ip_mask:
          - 10.0.0.0 255.0.0.0
          - 172.16.0.0 255.240.0.0
          - 192.168.0.0 255.255.0.0
      register: output

    - name: "TASK 3: Print output of show interfaces"
      debug:
        msg: "{{ output.stdout_lines.0 }}"

    - name: "TASK 3: Print output of pinging Google DNS"
      debug:
        msg: "{{ output.stdout_lines.1 }}"
